# application-dev.properties (for Docker Compose)
spring.application.name=workflow-api

# Connect to postgres service (container network)
spring.datasource.url=jdbc:postgresql://postgres:5432/workflow_dev
spring.datasource.username=wf_user
spring.datasource.password=wf_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
logging.level.org.springframework.security=DEBUG
# Actuator
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.client-name=Google
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google
server.port=8080
frontend.url=http://localhost:5173
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
management.endpoints.prometheus.enabled=true
app.queue.workflow-runs=workflow.runs

management.endpoint.prometheus.access=unrestricted
management.endpoint.health.access=unrestricted
management.endpoint.info.access=unrestricted

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.endpoints.web.base-path=/actuator
management.server.port=8080